routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('wallet', 'HomeController@wallet')->name('wallet');

Route::group(['middleware' => 'auth'], function () {

	Route::get('results', 'ResultController@index')->name('results.all');
	
	Route::resource('uploads/{hash}/results', 'ResultController');
	
	Route::resource('uploads', 'UploadController');

	Route::post('uploads/{hash}/results/export', 'ResultController@export')->name('results.export');
	Route::resource('payments', 'PaymentController');

	Route::resource('charges', 'ChargeController');

	Route::get('settings', 'SettingsController@index')->name('settings.index');
	Route::post('settings/grades', 'SettingsController@updateGrades')->name('settings.grades.update');
	Route::post('settings/aggt', 'SettingsController@updateAggt')->name('settings.aggt.update');

	Route::get('settings/profile', 'SettingsController@showProfile')->name('profile.show');
	Route::post('settings/profile', 'SettingsController@updateProfile')->name('profile.update');
	Route::get('settings/account', 'SettingsController@showAccount')->name('account.show');
	Route::post('settings/account', 'SettingsController@updateAccount')->name('account.update');
});

Route::post('download-sample', 'UploadController@downloadSample')->name('download-sample');

resources/views/home.blade.php
@extends('layouts.dashboard')

@section('title', 'Home')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-warning text-center">
                                    <i class="ti-upload"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Uploads</p>
                                    {{ Auth::user()->uploadsCount() }}
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr/>
                            <div class="stats">
                                <a href="{{ route('uploads.create') }}" class="btn btn-primary">Upload</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-warning text-center">
                                    <i class="ti-user"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Results</p>
                                    {{ Auth::user()->resultsCount() }}
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr/>
                            <div class="stats">
                                <a href="{{ route('results.all') }}" class="btn btn-primary">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-success text-center">
                                    <i class="ti-wallet"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Balance</p>
                                    TZS{{ number_format(Auth::user()->balance) }}
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <a href="{{ route('wallet') }}" class="btn btn-primary">Top Up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-success text-center">
                                    <i class="ti-bar-chart"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Expenditure</p>
                                    TZS{{ number_format(Auth::user()->expenditure()) }}
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <a href="{{ route('charges.index') }}" class="btn btn-primary">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
@endsection

resources/views/wallet.blade.php
@extends('layouts.dashboard')

@section('title', 'Wallet')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-success text-center">
                                    <i class="ti-wallet"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Balance</p>
                                    TZS{{ number_format(Auth::user()->balance) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>        
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Top Up</h4>
                    </div>
                    <div class="content">
                        
                        <div class="row">
                            <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                                <form>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-3 col-xs-12">
                                                <label>Payment Method</label>
                                                <select class="form-control">
                                                    <option value="">Airtel Money</option>
                                                    <option value="">Halo Pesa</option>
                                                    <option value="">MPesa</option>
                                                    <option value="">Tigo Pesa</option>
                                                </select>
                                            </div>
                                            <div class="col-sm-5 col-xs-12">
                                                <label>Phone number</label>
                                                <input type="text" name="phone" id="phone" placeholder="Phone number" class="form-control border-input">
                                                <p class="help-block text-muted">
                                                    Start with zero
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-primary">Pay</button>
                                </form>                                
                            </div>
                        </div>
                      
                    </div>
                </div>
            </div>


        </div>
    </div>
@endsection