routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('wallet', 'HomeController@wallet')->name('wallet');

Route::group(['middleware' => 'auth'], function () {

	Route::get('results', 'ResultController@index')->name('results.all');
	
	Route::resource('uploads/{hash}/results', 'ResultController');
	
	Route::resource('uploads', 'UploadController');

	Route::post('uploads/{hash}/results/export', 'ResultController@export')->name('results.export');
	Route::resource('payments', 'PaymentController');

	Route::resource('charges', 'ChargeController');

	Route::get('settings', 'SettingsController@index')->name('settings.index');
	Route::post('settings/grades', 'SettingsController@updateGrades')->name('settings.grades.update');
	Route::post('settings/aggt', 'SettingsController@updateAggt')->name('settings.aggt.update');

	Route::get('settings/profile', 'SettingsController@showProfile')->name('profile.show');
	Route::post('settings/profile', 'SettingsController@updateProfile')->name('profile.update');
	Route::get('settings/account', 'SettingsController@showAccount')->name('account.show');
	Route::post('settings/account', 'SettingsController@updateAccount')->name('account.update');
});

Route::post('download-sample', 'UploadController@downloadSample')->name('download-sample');

app/Charge.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Charge extends Model
{
    //
}

app/Http/Controllers/ChargeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ChargeController extends Controller
{
    public function index()
    {
    	$charges = auth()->user()->charges()->orderBy('created_at', 'DESC')->get();
    	return view('charges.index', compact('charges'));
    }
}

resources/views/charges/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Charges')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="content {{ $charges->count() ? 'table-responsive table-full-width' : '' }}">
                        @if($charges->count())
                            <table class="table table-striped">
                                <thead>
                                <th>ID</th>
                                <th>Upload</th>
                                <th>Candidates</th>
                                <th>Per Candidate</th>
                                <th class="text-right">Amount (TZS)</th>
                                <th>Date</th>
                                </thead>
                                <tbody>
                                @php $i = 1 @endphp
                                @foreach($charges as $charge)
                                    <tr>
                                        <td>{{ $i++ }}.</td>
                                        <td>
                                            <a href="{{ route('uploads.show', $charge->upload_hash) }}">
                                                {{ $charge->upload_hash }}
                                            </a>
                                        </td>
                                        <td>{{ $charge->candidates }}</td>
                                        <td>{{ $charge->per_candidate }}</td>
                                        <td class="text-right">{{ number_format($charge->total) }}</td>
                                        <td>{{ $charge->created_at }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="text-center">No Charges</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection