routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('wallet', 'HomeController@wallet')->name('wallet');

Route::group(['middleware' => 'auth'], function () {

	Route::get('results', 'ResultController@index')->name('results.all');
	
	Route::resource('uploads/{hash}/results', 'ResultController');
	
	Route::resource('uploads', 'UploadController');

	Route::post('uploads/{hash}/results/export', 'ResultController@export')->name('results.export');
	Route::resource('payments', 'PaymentController');

	Route::resource('charges', 'ChargeController');

	Route::get('settings', 'SettingsController@index')->name('settings.index');
	Route::post('settings/grades', 'SettingsController@updateGrades')->name('settings.grades.update');
	Route::post('settings/aggt', 'SettingsController@updateAggt')->name('settings.aggt.update');

	Route::get('settings/profile', 'SettingsController@showProfile')->name('profile.show');
	Route::post('settings/profile', 'SettingsController@updateProfile')->name('profile.update');
	Route::get('settings/account', 'SettingsController@showAccount')->name('account.show');
	Route::post('settings/account', 'SettingsController@updateAccount')->name('account.update');
});

Route::post('download-sample', 'UploadController@downloadSample')->name('download-sample');

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="#">@yield('title')</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {{--<li>--}}
                    {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                        {{--<i class="ti-panel"></i>--}}
                        {{--<p>Stats</p>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="dropdown">--}}
                    {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                        {{--<i class="ti-bell"></i>--}}
                        {{--<p class="notification">5</p>--}}
                        {{--<p>Notifications</p>--}}
                        {{--<b class="caret"></b>--}}
                    {{--</a>--}}
                    {{--<ul class="dropdown-menu">--}}
                        {{--<li><a href="#">Notification 1</a></li>--}}
                        {{--<li><a href="#">Notification 2</a></li>--}}
                        {{--<li><a href="#">Notification 3</a></li>--}}
                        {{--<li><a href="#">Notification 4</a></li>--}}
                        {{--<li><a href="#">Another notification</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}
                <li>
                    <a href="{{ route('settings.index') }}">
                        <i class="ti-settings"></i>
                        <p>Settings</p>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

resources/views/partials/sidebar.blade.php
<ul class="nav">
    <li class="{{ Request::is('home') ? 'active' : '' }}">
        <a href="{{ route('home') }}">
            <i class="ti-panel"></i>
            <p>Home</p>
        </a>
    </li>
    <li class="{{ Request::is('uploads') ? 'active' : '' }}">
        <a href="{{ route('uploads.index') }}">
            <i class="ti-upload"></i>
            <p>Uploads</p>
        </a>
    </li>
    <li class="{{ Request::is('results') ? 'active' : '' }}">
        <a href="{{ route('results.all') }}">
            <i class="ti-files"></i>
            <p>Results</p>
        </a>
    </li>
    <li class="{{ Request::is('wallet') ? 'active' : '' }}">
        <a href="{{ route('wallet') }}">
            <i class="ti-wallet"></i>
            <p>Wallet</p>
        </a>
    </li>
    <li class="{{ Request::is('charges') ? 'active' : '' }}">
        <a href="{{ route('charges.index') }}">
            <i class="ti-exchange-vertical"></i>
            <p>Charges</p>
        </a>
    </li>
    <li class="{{ Request::is('payments') ? 'active' : '' }}">
        <a href="{{ route('payments.index') }}">
            <i class="ti-money"></i>
            <p>Payments</p>
        </a>
    </li>
    <li class="{{ Request::is('settings/profile') ? 'active' : '' }}">
        <a href="{{ route('profile.show') }}">
            <i class="ti-user"></i>
            <p>Profile</p>
        </a>
    </li>    
    <li class="{{ Request::is('settings/account') ? 'active' : '' }}">
        <a href="{{ route('account.show') }}">
            <i class="ti-settings"></i>
            <p>Account</p>
        </a>
    </li>
    <li class="active-pro">
        <a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            <i class="ti-export"></i>
            <p>Logout</p>
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
    </li>        
</ul>