routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('wallet', 'HomeController@wallet')->name('wallet');

Route::group(['middleware' => 'auth'], function () {

	Route::get('results', 'ResultController@index')->name('results.all');
	
	Route::resource('uploads/{hash}/results', 'ResultController');
	
	Route::resource('uploads', 'UploadController');

	Route::post('uploads/{hash}/results/export', 'ResultController@export')->name('results.export');
	Route::resource('payments', 'PaymentController');

	Route::resource('charges', 'ChargeController');

	Route::get('settings', 'SettingsController@index')->name('settings.index');
	Route::post('settings/grades', 'SettingsController@updateGrades')->name('settings.grades.update');
	Route::post('settings/aggt', 'SettingsController@updateAggt')->name('settings.aggt.update');

	Route::get('settings/profile', 'SettingsController@showProfile')->name('profile.show');
	Route::post('settings/profile', 'SettingsController@updateProfile')->name('profile.update');
	Route::get('settings/account', 'SettingsController@showAccount')->name('account.show');
	Route::post('settings/account', 'SettingsController@updateAccount')->name('account.update');
});

Route::post('download-sample', 'UploadController@downloadSample')->name('download-sample');

app/Upload.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Upload extends Model
{
    public function result()
    {
    	return $this->hasOne(Result::class);
    }

    public function candidates($hash)
    {
    	return auth()->user()->uploads()->whereHash($hash)->count();
    }
}

app/Http/Controllers/UploadController.php
<?php

namespace App\Http\Controllers;

use App\Upload;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class UploadController extends Controller
{
    public function index()
    {
        $uploads = auth()->user()->uploads()->distinct('hash')->orderBy('created_at', 'DESC')->get(['hash', 'created_at']);

        return view('uploads.index', compact('uploads'));
    }

    public function show($hash)
    {
        $uploads = auth()->user()->uploads()->whereHash($hash)->get();

        return view('uploads.show', compact('hash', 'uploads'));
    }

    public function create()
    {
        return view('uploads.create');
    }

    public function store(Request $request)
    {
        $hash = str_random(10);

        // validate

        $rows = Excel::load($request->file('file'), function ($reader) {

        })->get();

        $time = Carbon::now();

        foreach ($rows as $row) {
            $upload = new Upload;
            $upload->user_id = auth()->id();
            $upload->hash = $hash;
            $upload->student_name = $row->student_name;
            $upload->civ = $row->civ;
            $upload->hist = $row->hist;
            $upload->geo = $row->geo;
            $upload->kisw = $row->kisw;
            $upload->engl = $row->engl;
            $upload->phy = $row->phy;
            $upload->chem = $row->chem;
            $upload->bio = $row->bio;
            $upload->bmath = $row->bmath;
            $upload->created_at = $time;
            $upload->updated_at = $time;
            $upload->save();
        }

        notify()->flash('Upload success');

        return redirect()->route('uploads.index');
    }

    public function downloadSample()
    {
        return response()->download(public_path('/samples/sample-students.xlsx'));
    }
}

resources/views/uploads/create.blade.php
@extends('layouts.dashboard')

@section('title', 'New Upload')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">New Upload</h4>
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                <form action="{{ route('uploads.store') }}" method="POST" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    
                                    <div class="form-group">
                                        <input type="file" name="file" required>
                                    </div>
                                    
                                    <button type="submit" class="btn btn-info btn-fill btn-wd">Upload</button>

                                </form>                                
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                                <p class="text-muted">
                                    Please upload an excel file containing names of students and their results.
                                    Follow the format below otherwise it will not work
                                </p>
                                <form action="{{ route('download-sample') }}" method="POST">
                                    {{ csrf_field() }}

                                    <button type="submit" class="btn btn-default">Download Sample</button>
                                </form>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

@endsection

resources/views/uploads/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Uploads')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="card">
                    <div class="content">
                        <a href="{{ route('uploads.create') }}" class="btn btn-primary">Upload</a>
                    </div>  
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="content {{ $uploads->count() ? 'table-responsive table-full-width' : '' }}">
                        @if($uploads->count())
                            <table class="table table-striped">
                                <thead>
                                <th>ID</th>
                                <th>Upload</th>
                                <th>Candidates</th>
                                <th>Date</th>
                                </thead>
                                <tbody>
                                @php $i = 1 @endphp
                                @foreach($uploads as $upload)
                                    <tr>
                                        <td>{{ $i++ }}.</td>
                                        <td>
                                            <a href="{{ route('uploads.show', $upload->hash) }}">
                                                {{ $upload->hash }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $upload->candidates($upload->hash) }}
                                        </td>
                                        <td>
                                            {{ $upload->created_at }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="text-center">No Upload</p>
                        @endif
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/uploads/show.blade.php
@extends('layouts.dashboard')

@section('title', 'Uploads')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="card">
                    <div class="content">
                        @if(Auth::user()->paid($hash))
                            <a href="{{ route('results.index', $hash) }}" class="btn btn-primary">View Results</a>
                        @else
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Candidates</th>
                                            <th>Per Candidate (TZS)</th>
                                            <th>Amount (TZS)</th>
                                            <th>Your Balance (TZS)</th>
                                            @if(Auth::user()->balance < $amount = ($uploads->count() * config('billing.per_candidate')))
                                                <th>Required (TZS)</th>
                                            @endif
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ $uploads->count() }}</td>
                                            <td>{{ config('billing.per_candidate') }}</td>
                                            <td>
                                                ({{ $uploads->count() }}
                                                x
                                                {{ number_format(config('billing.per_candidate')) }})
                                                =
                                                {{ number_format($amount) }}
                                            </td>
                                            <td> {{ number_format(Auth::user()->balance) }}</td>
                                            @if(Auth::user()->balance < $amount)
                                                <td>
                                                    {{ number_format($amount - Auth::user()->balance) }}
                                                </td>
                                            @endif
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                            @if (Auth::user()->balance >= ($uploads->count() * config('billing.per_candidate')))
                                <form action="{{ route('results.store', $hash) }}" method="POST">
                                    {{ csrf_field() }}

                                    <button type="submit" class="btn btn-primary">Process Results</button>
                                </form>
                            @else
                                <button type="button" class="btn btn-primary" disabled>Generate Results</button>
                                <p>You have insufficient balance. Please top up your balance to be able to generate results.</p>
                            @endif
                        @endif

                    </div>  
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="content table-responsive table-full-width">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <th>ID</th>
                            <th>CANDIDATE NAME</th>
                            <th>DETAILED SUBJECTS</th>
                            </thead>
                            <tbody>
                            @php $i = 1 @endphp
                            @foreach($uploads as $upload)
                                <tr>
                                    <td>{{ $i++ }}.</td>
                                    <td>{{ $upload->student_name }}</td>
                                    <td>
                                        CIV-{{ number_format($upload->civ) }}
                                        HIST-{{ number_format($upload->hist) }}
                                        GEO-{{ number_format($upload->geo) }}
                                        KISW-{{ number_format($upload->kisw) }}
                                        ENGL-{{ number_format($upload->engl) }}
                                        PHY-{{ number_format($upload->phy) }}
                                        CHEM-{{ number_format($upload->chem) }}
                                        BIO-{{ number_format($upload->bio) }}
                                        B/MATH-{{ number_format($upload->bmath) }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection